from pathlib import Path
source=Path(__file__).with_name('animate_walk.py').read_text()
source=source.replace("OUT=ROOT/'walk_cycle'","OUT=ROOT/'walk_natural'")
source=source.replace("cape=set(); visited=set()","cape=set(); shoulder=set(); visited=set()")
source=source.replace("if min(p.z for p in pts)<.4", "if max(abs(p.x) for p in pts)>.27 and min(p.z for p in pts)>.98: shoulder.update(comp)\n   if min(p.z for p in pts)<.4")
source=source.replace("weights=blend('Chest','UpperArm.'+l", "weights=blend('Shoulder.'+l,'UpperArm.'+l")
source=source.replace("elif vert.index in cape:","elif vert.index in shoulder: weights={'Shoulder.'+l:1}\n  elif vert.index in cape:")
source=source.replace("hip.location.z=-.025+.008*math.cos(2*phase)","hip.location.y=-.021+.006*math.cos(2*phase)\n hip.location.x=-.007*math.sin(phase)\n local_worldrot('Hips',Quaternion((0,0,1),math.radians(2.2)*math.cos(phase))@Quaternion((0,1,0),math.radians(.85)*math.sin(phase)))\n local_worldrot('Spine',Quaternion((0,0,1),-math.radians(1.0)*math.cos(phase-.12))@Quaternion((0,1,0),-math.radians(1.0)*math.sin(phase-.12))@Quaternion((1,0,0),math.radians(1.0)+math.radians(.35)*math.cos(2*phase-.3)))")
source=source.replace("local_worldrot('Chest',Quaternion((0,0,1),.025*math.sin(phase)))","local_worldrot('Chest',Quaternion((0,0,1),-math.radians(4.0)*math.cos(phase-.20))@Quaternion((0,1,0),-math.radians(1.2)*math.sin(phase-.12)))")
source=source.replace("local_worldrot('Head',Quaternion((0,0,1),-.012*math.sin(phase)))","local_worldrot('Head',Quaternion((0,0,1),math.radians(2.3)*math.cos(phase-.20))@Quaternion((0,1,0),math.radians(1.1)*math.sin(phase-.12)))")
source=source.replace("hb=arm.bones['UpperLeg.'+l].head_local.copy()+Vector((0,0,hip.location.z))","hb=rig.pose.bones['UpperLeg.'+l].head.copy()")
source=source.replace(".105+.062*swing", ".105+.038*swing")
source=source.replace("q=Quaternion((1,0,0),-.21*math.cos(p))", "local_worldrot('Shoulder.'+l,Quaternion((0,0,1),-s*math.radians(1.4)*math.cos(p-.15))@Quaternion((0,1,0),s*math.radians(.6)*math.sin(p)))\n  q=Quaternion((1,0,0),-.18*math.cos(p-.12))")
source=source.replace("local_worldrot('LowerArm.'+l,Quaternion((0,0,1),-s*.12))", "elbow=math.radians(7+3*math.cos(p-.38))\n  local_worldrot('LowerArm.'+l,Quaternion((0,0,1),-s*elbow))\n  local_worldrot('Hand.'+l,Quaternion((0,0,1),s*math.radians(1.3)*math.sin(p-.55)))")
source=source.replace("'Walk_InPlace'","'Walk_Subtle_InPlace'")
exec(compile(source,'animate_walk_natural_generated','exec'))
